import nh3

EMAIL_TAGS = {
    "a",
    "br",
    "div",
    "em",
    "h1",
    "h2",
    "h3",
    "hr",
    "img",
    "li",
    "ol",
    "p",
    "span",
    "strong",
    "table",
    "tbody",
    "td",
    "th",
    "thead",
    "tr",
    "ul",
}

EMAIL_ATTRIBUTES = {
    "*": {"class", "style"},
    "a": {"data-codrut-cta", "href", "target", "title"},
    "img": {"alt", "height", "src", "title", "width"},
    "table": {"cellpadding", "cellspacing", "role", "width"},
    "td": {"align", "colspan", "rowspan", "valign", "width"},
    "th": {"align", "colspan", "rowspan", "scope", "valign", "width"},
}

EMAIL_STYLE_PROPERTIES = {
    "background",
    "background-color",
    "border",
    "border-bottom",
    "border-collapse",
    "border-color",
    "border-left",
    "border-radius",
    "border-right",
    "border-style",
    "border-top",
    "border-width",
    "box-shadow",
    "color",
    "display",
    "font-family",
    "font-size",
    "font-style",
    "font-weight",
    "height",
    "letter-spacing",
    "line-height",
    "margin",
    "margin-bottom",
    "margin-left",
    "margin-right",
    "margin-top",
    "max-width",
    "overflow",
    "padding",
    "padding-bottom",
    "padding-left",
    "padding-right",
    "padding-top",
    "text-align",
    "text-decoration",
    "vertical-align",
    "width",
}


def sanitize_email_html(value: str) -> str:
    return nh3.clean(
        value,
        tags=EMAIL_TAGS,
        clean_content_tags={"script", "style", "svg", "math", "iframe", "object", "embed"},
        attributes=EMAIL_ATTRIBUTES,
        strip_comments=True,
        link_rel="noopener noreferrer",
        url_schemes={"http", "https", "mailto"},
        filter_style_properties=EMAIL_STYLE_PROPERTIES,
        url_relative="deny",
    )
