"""create_email_templates

Revision ID: 32c91b8faa10
Revises: 4102edafb8c7
Create Date: 2026-06-06 07:51:15.024262
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '32c91b8faa10'
down_revision: str | None = '4102edafb8c7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('html_body', sa.String(), nullable=False),
    sa.Column('text_body', sa.String(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=False),
    sa.Column('audience', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.Column(
        'updated_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.ForeignKeyConstraint(
        ['owner_id'],
        ['users.id'],
        name=op.f('fk_email_templates_owner_id_users'),
        ondelete='SET NULL',
    ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_templates')),
    sa.UniqueConstraint('key', 'version', name='uq_email_templates_key_version')
    )
    op.create_index(
        op.f('ix_email_templates_owner_id'),
        'email_templates',
        ['owner_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_templates_owner_id'), table_name='email_templates')
    op.drop_table('email_templates')
    # ### end Alembic commands ###
