"""create_assignment_invites

Revision ID: 59a90d317c62
Revises: 32c91b8faa10
Create Date: 2026-06-06 11:32:15.303446
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '59a90d317c62'
down_revision: str | None = '32c91b8faa10'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_invites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('respondent_profile_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.Column(
        'updated_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.ForeignKeyConstraint(
        ['company_id'],
        ['companies.id'],
        name=op.f('fk_assignment_invites_company_id_companies'),
        ondelete='CASCADE',
    ),
    sa.ForeignKeyConstraint(
        ['respondent_profile_id'],
        ['participant_profiles.id'],
        name=op.f('fk_assignment_invites_respondent_profile_id_participant_profiles'),
        ondelete='CASCADE',
    ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignment_invites'))
    )
    op.create_index(
        op.f('ix_assignment_invites_company_id'),
        'assignment_invites',
        ['company_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_assignment_invites_respondent_profile_id'),
        'assignment_invites',
        ['respondent_profile_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_assignment_invites_token'),
        'assignment_invites',
        ['token'],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignment_invites_token'), table_name='assignment_invites')
    op.drop_index(
        op.f('ix_assignment_invites_respondent_profile_id'),
        table_name='assignment_invites',
    )
    op.drop_index(op.f('ix_assignment_invites_company_id'), table_name='assignment_invites')
    op.drop_table('assignment_invites')
    # ### end Alembic commands ###
