"""add_error_details_to_email_send

Revision ID: d60b3aab2766
Revises: 59a90d317c62
Create Date: 2026-06-06 12:08:58.146564
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision: str = 'd60b3aab2766'
down_revision: str | None = '59a90d317c62'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_sends', sa.Column('error_details', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_sends', 'error_details')
    # ### end Alembic commands ###
